name: RenderingLib
description: Rendering without the doll parts
version: 2.8.1
homepage: https://github.com/FarragoFiction/RenderingLib
author: jadedResearcher, paradoxLands

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  js: any
  CommonLib:
    git: git://github.com/FarragoFiction/CommonLib.git
  LoaderLib:
    git: git://github.com/FarragoFiction/LoaderLib.git

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0