name: RenderingLib
description: Rendering without the doll parts
version: 2.2.0
homepage: https://github.com/FarragoFiction/RenderingLib
author: jadedResearcher, paradoxLands

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  js: any
  CommonLib:
    git: git://github.com/FarragoFiction/CommonLib.git
  LoaderLib:
    git: git://github.com/FarragoFiction/LoaderLib.git

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0

web:
  compiler:
    debug: dartdevc