name: RenderingLib
description: Rendering without the doll parts
version: 2.8.1
homepage: https://github.com/FarragoFiction/RenderingLib
author: jadedResearcher, paradoxLands

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  js: any
  CommonLib:
    git: 
      url: git://github.com/FarragoFiction/CommonLib.git
      ref: Dart-2.8.1
  LoaderLib:
    git:
      url: git://github.com/FarragoFiction/LoaderLib.git
      ref: Dart-2.8.1

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0