name: RenderingLib
description: Rendering without the doll parts
version: 0.0.2
homepage: https://github.com/FarragoFiction/RenderingLib
author: jadedResearcher, paradoxLands

environment:
  sdk: '>=1.24.1 <2.0.0'

dependencies:
  js: ^0.6.0
  CommonLib:
    git: git://github.com/FarragoFiction/CommonLib.git
  LoaderLib:
    git: git://github.com/FarragoFiction/LoaderLib.git

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- $dart2js:
    sourceMaps: true
    commandLineOptions: [--fast-startup, --trust-type-annotations]